### ISSUE TITLE
API error when using github_team data resource causes hard error.

### ISSUE THREAD

**Issue by joestump** [terraform-providers/terraform-provider-github#42] opened 2017-07-26 22:18 UTC
### Terraform Version

0.9.11

### Affected Resource(s)

The `github_team` data resource.

### Terraform Configuration Files

```hcl
variable "GITHUB_TOKEN" {}

provider "github" {
  token        = "${var.GITHUB_TOKEN}"
  organization = "krux"
}

data "github_team" "ci" {
  slug = "ci"
}

output "name" {
  value = "${data.github_team.ci.name}"
}
```

### Panic Output

https://gist.github.com/joestump/540e3ce37156715f0e08f38419c3c4c5

### Expected Behavior

It should pull in the team's info.

### Actual Behavior

TF crashes.

### Steps to Reproduce

I haven't been able to 100% nail this down other than it works for teams when I'm an owner of an organization, but doesn't for another organization that I'm just a member of. 

_However..._ 

When I use the same token `GITHUB_TOKEN` I pass to Terraform via `curl` it works:

```
# Returns a 200 and a list of teams. Identical request above in TF fails.
curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/orgs/krux/teams
```

### Important Factoids

I think what's happening is that the API call to list teams is failing for an unknown reason and then TF fails hard when it hits this line:

https://github.com/terraform-providers/terraform-provider-github/blob/master/github/data_source_github_team.go#L84

I don't believe `team` is defined there? It should probably be `return nil, err`? (Sorry, I'm not great at Go, so ignore if it's a red herring.)

**Comment by radeksimko** [comment] 2018-08-03 12:35
Hi @joestump 
thanks for the report and sorry for the delay in processing it.

This appears to be a crash caused by the fact that we tried to dereference description which was `nil` (i.e. we expected a team to always have a non-empty description).

https://github.com/hashicorp/terraform/blob/v0.9.11/builtin/providers/github/data_source_github_team.go#L55

This was addressed in https://github.com/terraform-providers/terraform-provider-github/pull/2 which shipped last year as `0.1.0` (first release after the provider split).

For that reason I believe it's fixed and I'm going to close this issue. Let us know if the problem persists.

**Closed by radeksimko** 2018-08-03 12:35 UTC
Labels: bug, crash
