### ISSUE TITLE
SIGSEGV while importing github_branch_protection

### ISSUE THREAD

**Issue by mchesler** [terraform-providers/terraform-provider-github#386] opened 2020-03-14 22:14 UTC
### Terraform Version
```
Terraform v0.12.18
+ provider.github v2.4.1
```

### Affected Resource(s)
- github_branch_protection

### Terraform Configuration Files
```hcl
provider "github" {
  organization = "my_org"
}

terraform {
  backend "s3" {
    bucket         = "my_bucket"
    key            = "global/github.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "terraform-lock"
  }
}

resource "github_repository" "repository" {
  name = "repository"
}

resource "github_branch_protection" "repository_master" {
  repository = github_repository.repository.name
  branch     = "master"
}
```

### Debug Output
https://gist.github.com/mchesler/6f1b6981640b8dd56ab5108d05e6f7d5#file-debug-out

### Panic Output
https://gist.github.com/mchesler/6f1b6981640b8dd56ab5108d05e6f7d5#file-crash-log

### Expected Behavior
Import should have succeeded

### Actual Behavior
Plugin panicked

### Steps to Reproduce
`terraform import github_branch_protection.repository_master repository:master`

### Important Factoids
None come to mind

### References
Was not able to find any tickets that described the same issue

**Comment by borysbabii** [comment] 2020-03-16 14:18
I faced the same issue on `v2.4.1`, downgrade to `v2.4.0` solved the issue.

**Comment by antonbabenko** [comment] 2020-03-19 20:25
Thanks @borysbabii for the solution!

**Comment by anGie44** [comment] 2020-03-25 17:44
hi @jcudit! could this be safe to close? looks like https://github.com/terraform-providers/terraform-provider-github/pull/385 takes care of things :)

**Comment by hendrikhalkow** [comment] 2020-03-26 01:29
I also faced some `rpc error: code = Unavailable desc = transport is closing` error when applying a change to `github_branch_protection`. Downgrading to 2.4.0 worked for me, too.

**Comment by jcudit** [comment] 2020-03-26 14:21
I have this queued to reproduce / investigate but welcome any other contributors doing the same.  From what I can tell this is still an open issue and #385 addresses a separate case.

**Comment by claywd-bestow** [comment] 2020-03-26 16:02
Looking into this later tonight

**Comment by Claywd** [comment] 2020-03-26 16:02
Looking into this later today

**Comment by jcudit** [comment] 2020-04-02 01:49
I was not able to reproduce this on a first attempt:

```hcl
resource "github_repository" "repository" {
  name        = "acceptance-tests"
  description = "Acceptance Testing For `terraform-provider-github`"
}

resource "github_branch_protection" "repository_master" {
  repository = github_repository.repository.name
  branch     = "master"
}
```
```hcl
provider "github" {
  version      = "2.4.1"
  organization = var.organization
}
```
```hcl
organization = "terraformtesting"
environment  = "development"
```
```console
21:35:29 [jcudit:~/github … aform-github-terraform-repositories/examples/development] master* 14m24s ± terraform version
Terraform v0.12.18
+ provider.github v2.4.1

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from https://www.terraform.io/downloads.html
21:35:33 [jcudit:~/github … aform-github-terraform-repositories/examples/development] master* 14m28s ± terraform state rm github_branch_protection.repository_master
Removed github_branch_protection.repository_master
Successfully removed 1 resource instance(s).
21:35:46 [jcudit:~/github … aform-github-terraform-repositories/examples/development] master* 14m41s ± terraform import github_branch_protection.repository_master acceptance-tests:master
github_branch_protection.repository_master: Importing from ID "acceptance-tests:master"...
github_branch_protection.repository_master: Import prepared!
  Prepared github_branch_protection for import
github_branch_protection.repository_master: Refreshing state... [id=acceptance-tests:master]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

**Comment by jcudit** [comment] 2020-04-02 01:56
Digging into the attached stack trace ...

```console
 runtime error: invalid memory address or nil pointer dereference
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a0cb6c]
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: goroutine 69 [running]:
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: github.com/terraform-providers/terraform-provider-github/github.flattenAndSetRequiredPullRequestReviews(0xc000305340, 0xc00000bfc0, 0x0, 0x0)
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/github/resource_github_branch_protection.go:431 +0x4c
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: github.com/terraform-providers/terraform-provider-github/github.resourceGithubBranchProtectionRead(0xc000305340, 0x1ac3e60, 0xc0001fe7b0, 0xc000305340, 0x0)
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/github/resource_github_branch_protection.go:241 +0x9a7
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000180a80, 0xc0000d9220, 0x1ac3e60, 0xc0001fe7b0, 0xc0000ce7f0, 0x0, 0x0)
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:455 +0x11c
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000172538, 0x1eb3360, 0xc0001fe9f0, 0xc0000d9040, 0xc000172538, 0xc0001fe960, 0x1b71c80)
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:525 +0x3a8
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x1c9e520, 0xc000172538, 0x1eb3360, 0xc0001fe9f0, 0xc0000d8ff0, 0x0, 0x0, 0x0, 0xc0003be380, 0xd7)
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3181 +0x23e
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d3080, 0x1eb9800, 0xc0000d3b00, 0xc000234500, 0xc00016af60, 0x26f3bb0, 0x0, 0x0, 0x0)
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/vendor/google.golang.org/grpc/server.go:971 +0x4a2
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000d3080, 0x1eb9800, 0xc0000d3b00, 0xc000234500, 0x0)
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/vendor/google.golang.org/grpc/server.go:1250 +0xd61
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001700b0, 0xc0000d3080, 0x1eb9800, 0xc0000d3b00, 0xc000234500)
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/vendor/google.golang.org/grpc/server.go:690 +0x9f
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/vendor/google.golang.org/grpc/server.go:688 +0xa1
```

> 2020-03-14T18:06:30.760-0400 [DEBUG] plugin.terraform-provider-github_v2.4.1_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-github/github/resource_github_branch_protection.go:431 +0x4c

I now see that [resource_github_branch_protection.go:431](https://github.com/terraform-providers/terraform-provider-github/blob/v2.4.1/github/resource_github_branch_protection.go#L431) assumes the existence of `DismissalRestrictions`, which was addressed in https://github.com/terraform-providers/terraform-provider-github/pull/385.

Apologies for misevaluating this [before](https://github.com/terraform-providers/terraform-provider-github/issues/386#issuecomment-604458733).  This can indeed be closed 😳

**Closed by jcudit** 2020-04-02 01:56 UTC
Labels: bug, crash, good first issue, help wanted
