### ISSUE TITLE
Feature Request: Add support for individuals

### ISSUE THREAD

**Issue by keyboardarmy** [terraform-providers/terraform-provider-github#371] opened 2020-03-01 06:27 UTC
### Terraform Version
Terraform v0.12.20
+ provider.github v2.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository
- github_repository_collaborator
- github_repository_deploy_key
- github_repository_project
- github_repository_webhook

### Terraform Configuration Files
```hcl
provider "github" {
  token        = var.github_token
  individual   = true
}

variable "github_token" {
    type        = string
}

resource "github_repository" "example" {
    name        = "example"
    description = "My awesome codebase"
    private     = true
}
```

### Expected Behavior
A personal account for an individual/developer shouldn't be treated any different than an organization account. Creating/managing individual or multiple repos should be manageable as code.

### Actual Behavior
An individual can not create or configure a repository. This most basic of use cases doesn't work current and fails with:

```
github_repository.example: Creating...

Error: This resource requires GitHub organization to be set on the provider.

  on main.tf line 11, in resource "github_repository" "example":
  11: resource "github_repository" "example" {
```

### Steps to Reproduce
1. `terraform init`
1. `terraform plan`
1. `terraform apply`

### References
None

**Comment by jcudit** [comment] 2020-03-12 13:13
👋 thanks for raising this issue.  It looks to be a duplicate of https://github.com/terraform-providers/terraform-provider-github/issues/45.

My understanding is that a change like this would span many resources and would reverse some assumptions that are in place within the provider.  I am 💯 on board with the change, but we would need to take care to implement it safely.

Confusingly, I have just read a report that [this actually works](https://github.com/terraform-providers/terraform-provider-github/issues/45#issuecomment-596407734) after a recent upgrade to the latest version.  Can anyone else reproduce this behaviour?

**Comment by keyboardarmy** [comment] 2020-04-04 05:40
I still see the issue on a personal github account with:

```
Terraform v0.12.24
+ provider.github v2.6.0
```

**Comment by keyboardarmy** [comment] 2020-04-04 05:45
some reports in the linked ticket mention 2.4.0 or 2.4.1 but then I would loose GitHub action secret support added in 2.5

**Comment by anGie44** [comment] 2020-04-17 19:40
hi @keyboardarmy! the linked PR #428 is in-progress to support resources/data management at the individual level. it's possible not all resource/data are covered to support individuals in the PR atm..if you identify any additional resources, any comments on the PR would be greatly appreciated :)

**Closed** 2020-06-17 19:30 UTC
