### ISSUE TITLE
Add support for delete_branch_on_merge

### ISSUE THREAD

**Issue by jakebiesinger-onduo** [terraform-providers/terraform-provider-github#330] opened 2020-01-28 01:01 UTC
It would be great to have support for `delete_branch_on_merge`, which was added in `go-github` API v29. You'd have to do a version bump to get there.

### Affected Resource(s)
- github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "repo" {
  ...
  delete_branch_on_merge = true  # Not possible currently
}
```

Thanks!

**Comment by mwarkentin** [comment] 2020-01-28 15:32
Dupe of #264 ?

**Comment by jakebiesinger-onduo** [comment] 2020-01-28 15:57
Yep! Thanks.

**Closed** 2020-02-01 16:24 UTC
