### ISSUE TITLE
data race on repo creation

### ISSUE THREAD

**Issue by xchapter7x** [terraform-providers/terraform-provider-github#147] opened 2018-09-06 14:58 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
-> % terraform -v
Terraform v0.11.8

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository
- github_team_repository

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "github_repository" "Modular-MVVM" {
  name        = "Modular-MVVM"
  private     = true
  description = "null"
  has_wiki    = "true"
  has_downloads = "true"
  has_issues  = "true"
}

resource "github_team_repository" "Mobile-Modular-MVVM" {
  team_id    = "${github_team.Mobile.id}"
  repository = "Modular-MVVM"
  permission = "push"
}
```

### Debug Output
https://gist.github.com/xchapter7x/30ea644664487714e5648690641fa030

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should create the repo and then associate the team

### Actual Behavior
Creates the repo and then fails to associate the team saying repo doesn't exist

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Github API generally is eventually consistent, so this is likely a data race, if there are no checks or timeouts to validate a resource, like a repo, has been created.

**Comment by radeksimko** [comment] 2018-09-07 16:40
Hi @xchapter7x 
GitHub's API is indeed eventually consistent, but this is most likely caused by the fact that your configs don't use referencing syntax, which would normally hint Terraform how to schedule operations correctly, see modified config below.

```hcl
resource "github_repository" "Modular-MVVM" {
  name        = "Modular-MVVM"
  private     = true
  description = "null"
  has_wiki    = "true"
  has_downloads = "true"
  has_issues  = "true"
}

resource "github_team_repository" "Mobile-Modular-MVVM" {
  team_id    = "${github_team.Mobile.id}"
  repository = "${github_repository.Modular-MVVM.name}"
  permission = "push"
}
```
without these references Terraform has no way of knowing that `github_repository` should be created before `github_team_repository`.

I'm going to close this as I believe there is nothing to fix, but let me know if you keep running into problems and I'm happy to reopen.

**Closed by radeksimko** 2018-09-07 16:40 UTC
Labels: question

**Comment by xchapter7x** [comment] 2018-09-07 16:51
@radeksimko thanks. that makes total sense. if i still see issues ill let you know.
thanks again.
