### ISSUE TITLE
github_team_membership team_id not being imported

### ISSUE THREAD

**Issue by Jonnymcc** [terraform-providers/terraform-provider-github#324] opened 2020-01-16 21:11 UTC
### Terraform Version
Terraform v0.11.14
+ provider.github v2.2.1

### Affected Resource(s)
- github_team_membership

### Terraform Configuration Files
```hcl
resource "github_team" "Managers" {
  name        = "Managers"
  privacy     = "closed"
}

resource "github_team_membership" "Managers-Jonnymcc" {
  username = "Jonnymcc"
  team_id  = "${github_team.Managers.id}"
  role     = "member"
}
```

### Debug Output
```
github_team_membership.Merge_Managers-Jonnymcc: Destroying... (ID: xxxxx:Jonnymcc)

Error: Error applying plan:

1 error occurred:
	* github_team_membership.Merge_Managers-Jonnymcc (destroy): 1 error occurred:
	* github_team_membership.Merge_Managers-Jonnymcc: Unexpected ID format (""), expected numerical ID. strconv.ParseInt: parsing "": invalid syntax
```

### Expected Behavior
When running terraform show, the `github_team_membership` resource should have a `team_id` attribute value.

### Actual Behavior
The `team_id` = "".

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import github_team_membership.Managers-Jonnymcc xxxxx:Jonnymcc`
2. `terraform apply -target github_team_membership.Managers-Jonnymcc`

### References
Maybe this bug fix is related...
resource/github_team_membership: Validation of team_id (#253)

**Comment by samrees** [comment] 2020-01-16 21:23
duplicate of https://github.com/terraform-providers/terraform-provider-github/issues/323

**Comment by brandoncamenisch** [comment] 2020-01-16 21:39
Same issue for me as well :cry: just popped up this morning.

**Comment by radeksimko** [comment] 2020-01-22 12:11
Thank you @samrees for noticing, you are right.
I'm going to close this as a duplicate of #323 

I just merged a PR which fixes the bug and we will release it soon.

**Closed by radeksimko** 2020-01-22 12:11 UTC
