### ISSUE TITLE
Upgrading to the latest provider version causes repositories to be deleted and recreated

### ISSUE THREAD

**Issue by ctrom** [terraform-providers/terraform-provider-github#140] opened 2018-08-27 16:39 UTC
There appears to be a bug in the latest version of the github provider that causes it to destroy and recreate the repositories I've got in my config.

### Terraform Version
```
$ terraform -v
Terraform v0.11.8
+ provider.github v1.2.1
```

### Affected Resources
- github_repository

#### repositories.tf:
```hcl
module "mytest-repo" {
  source             = "modules/repository"
  name               = "mytest"
}
```
#### modules/repository/main.tf:
```hcl
resource "github_repository" "github_repository" {
  name               = "${var.name}"
  description        = "${var.description}"
  homepage_url       = "${var.homepageUrl}"
  private            = "${var.private}"
  has_issues         = "${var.enableIssueTracker}"
  has_wiki           = "${var.enableWiki}"
  allow_merge_commit = "${var.allowMergeCommits}"
  allow_squash_merge = "${var.allowSquashMerges}"
  allow_rebase_merge = "${var.allowRebaseMerges}"
  auto_init          = "${var.autoInit}"
  default_branch     = "${var.defaultBranch}"
  archived           = "${var.archived}"
}
```
#### modules/repository/variables.tf:
```hcl
variable "name" {
}
variable "description" {
  default     = ""
}
variable "homepageUrl" {
  default     = ""
}
variable "private" {
  default     = true
}
variable "enableIssueTracker" {
  default     = false
}
variable "enableWiki" {
  default     = false
}
variable "allowMergeCommits" {
  default     = true
}
variable "allowSquashMerges" {
  default     = true
}
variable "allowRebaseMerges" {
  default     = true
}
variable "autoInit" {
  default     = true
}
variable "defaultBranch" {
  default     = "master"
}
variable "archived" {
  default     = false
}
```

### Debug Output
```hcl
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

github_repository.github_repository: Refreshing state... (ID: mytest)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ module.mytest-repo.github_repository.github_repository (new resource required)
      id:                 "mytest" => <computed> (forces new resource)
      allow_merge_commit: "true" => "true"
      allow_rebase_merge: "true" => "true"
      allow_squash_merge: "true" => "true"
      archived:           "false" => "false"
      auto_init:          "true" => "true"
      default_branch:     "master" => "master"
      full_name:          "PeopleNet/mytest" => <computed>
      git_clone_url:      "git://github.com/PeopleNet/mytest.git" => <computed>
      has_downloads:      "true" => "false"
      has_issues:         "false" => "false"
      has_wiki:           "false" => "false"
      html_url:           "https://github.com/PeopleNet/mytest" => <computed>
      http_clone_url:     "https://github.com/PeopleNet/mytest.git" => <computed>
      name:               "mytest" => "mytest"
      private:            "true" => "true"
      ssh_clone_url:      "git@github.com:PeopleNet/mytest.git" => <computed>
      svn_url:            "https://github.com/PeopleNet/mytest" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.
```
### Expected Behavior
It should be possible to use terraform to manage repositories without the repos getting deleted and recreated.

### Actual Behavior
After upgrading to `v1.2.1` of provider.github, my existing state and config is forcing the deletion and recreation of my repositories.

**Comment by radeksimko** [comment] 2018-08-28 09:33
Hi @ctrom 
sorry for the troubles.

I'm going to try and reproduce this. I have a hunch that it's unrelated to the upgrade, but rather to a rename of your repository, which is something we can't quite deal with gracefully (yet). I may be wrong though.

Which version you were upgrading from?

**Comment by ctrom** [comment] 2018-08-28 15:44
I was using `v1.1.0` and pinning the provider version back to that eliminated the problem for me - my config is no longer recommending I delete my repos.

**Comment by jfharden** [comment] 2018-09-04 18:35
I'm also seeing this issue but through a different path.

I imported a github repo, locked to provider 1.1.0 the plan does not want to recreate the repo, but on version 1.2.1 it does:

In my module:
```
provider "github" {
  organization = "${var.organization}"
  version = "= 1.1.0"
}

resource "github_repository" "this" {
  name         = "${var.name}"
  description  = "${var.description}"
  private      = true
  has_issues   = false
  has_projects = false
  has_wiki     = false
  auto_init    = true
  archived     = false
}

variable "name" {
  type        = "string"
  description = "Repository name"
}

variable "description" {
  type        = "string"
  description = "Description of the repository"
}

variable "organization" {
  type        = "string"
  description = "Organization under which the project resides"
  default     = "orgname"
}
``` 

Plan on 1.1.2 includes
```
Terraform v0.11.7
+ provider.github v1.2.1
```

```diff
-/+ github_repository.this (new resource required)
      id:                 "orgname-repo" => <computed> (forces new resource)
      allow_merge_commit: "true" => "true"
      allow_rebase_merge: "true" => "true"
      allow_squash_merge: "true" => "true"
      archived:           "false" => "false"
      auto_init:          "" => "true" (forces new resource)
      default_branch:     "master" => <computed>
      description:        "Infrastructure as (repo) code" => "Infrastructure as (repo) code"
      full_name:          "orgname/orgname-repo" => <computed>
      git_clone_url:      "git://github.com/orgname/orgname-repo.git" => <computed>
      has_downloads:      "true" => "false"
      has_issues:         "true" => "false"
      has_projects:       "" => "false"
      has_wiki:           "true" => "false"
      html_url:           "https://github.com/orgname/orgname-repo" => <computed>
      http_clone_url:     "https://github.com/orgname/orgname-repo.git" => <computed>
      name:               "orgname-repo" => "orgname-repo"
      private:            "true" => "true"
      ssh_clone_url:      "git@github.com:orgname/orgname-repo.git" => <computed>
      svn_url:            "https://github.com/orgname/orgname-repo" => <computed>
```

Plan when locked to 1.1.0 (the changes here are expected, important to note it doesn't want to change the id)

```
Terraform v0.11.7
+ provider.github v1.1.0
```

```diff
  ~ github_repository.this
      auto_init:      "" => "true"
      has_downloads:  "true" => "false"
      has_issues:     "true" => "false"
      has_projects:   "" => "false"
      has_wiki:       "true" => "false"
```

**Comment by radeksimko** [comment] 2018-09-05 11:27
@ctrom I'm struggling to reproduce this. Do you mind running `terraform plan` with [debugging mode](https://www.terraform.io/docs/internals/debugging.html) enabled (via `TF_LOG` & `TF_LOG_PATH` env variables) and providing the debug log? You may use our GPG key to encrypt it and/or send it privately to radek@hashicorp.com if you worry about sensitive data in that log.

-----

@jfharden I believe the behaviour you described is (unfortunately) expected since you're importing an existing repository and the GitHub API doesn't tell us whether the repository was auto-initialized, so we have no way of knowing whether to set `auto_init` to true or false when importing that resource.

We have discussed some long-term plans on improving the (currently limited) important functionality, but I'm afraid there isn't much better solution other than setting `auto_init = false` in your config after importing that resource _for now_.

Prior to the `1.2` that field appeared updatable, but was in fact ignored, which may have caused some confusions and bugs. So the previous behaviour was actually wrong and now is fixed.

**Comment by ctrom** [comment] 2018-09-11 04:10
@radeksimko I'm not sure what occurred to resolve this issue. I updated to the 1.2.1 version of this provider again and was also unable to replicate the behavior that I was seeing before. When I was experiencing this prior, I tested it on two different machines to ensure that the behavior wasn't unique to my configuration. Thank you anyway for taking the time to investigate this.

**Comment by radeksimko** [comment] 2018-09-11 05:35
Understood, I'm sorry I wasn't able to reproduce this, but I'm going to close the issue then, as there's currently nothing we can do.

Thanks.

**Closed by radeksimko** 2018-09-11 05:35 UTC
Labels: bug, waiting-response
