### ISSUE TITLE
Remove auth requirement for provider

### ISSUE THREAD

**Issue by julianvmodesto** [terraform-providers/terraform-provider-github#230] opened 2019-05-22 20:51 UTC
I'd like to consume only the [github_ip_ranges](https://www.terraform.io/docs/providers/github/d/ip_ranges.html) data source, but the provider requires setting an Organization and Token.

Would it be possible to remove this requirement?

**Comment by majormoses** [comment] 2019-06-07 00:51
duplicate of #190  and proposed as #191

**Comment by tracypholmes** [comment] 2019-07-16 20:15
Hi, @julianvmodesto! Thank you for opening this issue. This is being closed as a duplicate of #190.

**Closed by tracypholmes** 2019-07-16 20:15 UTC
Labels: duplicate, question
