### ISSUE TITLE
Webhook secret set via Terraform makes signatures not match

### ISSUE THREAD

**Issue by Tenzer** [terraform-providers/terraform-provider-github#171] opened 2018-11-29 17:26 UTC
### Terraform Version
Terraform v0.11.10
+ provider.archive v1.1.0
+ provider.aws v1.49.0
+ provider.github v1.3.0

### Affected Resource(s)
- github_organization_webhook
- github_repository_webhook (assumed, not tested)

### Terraform Configuration Files
```hcl
resource "github_organization_webhook" "webhook" {
  name   = "web"
  events = ["*"]

  configuration {
    url          = "${aws_api_gateway_deployment.github_notifications.invoke_url}"
    content_type = "json"
    secret       = "${local.github_secret}"
    insecure_ssl = false
  }
}
```

### Expected Behavior
I should be able to verify the body of the incoming webhook requests against the signature in the header, using the secret specified in the GitHub webhook.

### Actual Behavior
The signatures never match.

---

I first looked at a bunch of different implementations of GitHub webhook receivers to check if my implementation of the HMAC signature verification was wrong in some way but couldn't find any problems with it. I then tried to set the secret for the webhook directly in GitHub's web UI and then all signatures matched after that.
I tried to make some change to the hook with Terraform and could confirm that the signature then no longer would match again until I set the secret via the GitHub web UI again.

This is a bit tricky to debug further, as I can't see the secret that is being sent to GitHub as part of the TRACE debug output and I can't see the secret in GitHub either, but my only conclusion so far is that Terraform sets the secret to something else than the string I tell it to.

A curiosity is that the secret never is updated in the GitHub hook even though I change it in the configuration - at least from what the output of Terraform show - I don't know if this could be related, that the secret is set to something invalid whenever another change is made to the webhook?

**Comment by sryabkov** [comment] 2019-03-07 00:04
I think I am experiencing the same issue.  I initially set the repo webhook manually using GitHub UI, and the webhook was firing correctly. I then tried doing it through TF using the same value. `terraform plan` reported that it wanted to update the value. I ran `terraform apply`, after which the webhook started failing. I had to manually reset the secret value using GitHub UI to fix the webhook. 

It does look like the value of `secret` for a repo webhook is not set correctly when using the GitHub TF provider.

**Comment by niedbalski** [comment] 2019-03-28 21:53
Experiencing the same exact bug. +1

**Comment by niedbalski** [comment] 2019-04-03 00:42
Well, this is reproducible with 0.11.13 and current master. I think the best approach would be for the config schema to be forcenew = true and remove the diffsupress entirely.

**Comment by johne** [comment] 2019-06-12 17:21
it looks like it is setting the secret to 8 stars ("********") but only on an update not on the initial create... 

interestingly enough, the unit tests for the provider sets the secret to 8 stars ("********")... i'm not sure if that is a coincidence...

**Comment by megan07** [comment] 2019-07-15 14:33
Thanks @Tenzer for opening this issue. It's been closed with #251 and will be released shortly.

**Closed by megan07** 2019-07-15 14:33 UTC
Labels: bug

**Comment by Tenzer** [comment] 2019-07-15 14:39
You're welcome. Thank you for fixing this bug!

**Comment by kevinburkemeter** [comment] 2019-10-08 22:13
Couldn't find this on Google even though it fit my problem to a T so going to try to add some text to see if it fits... my coworker noticed `github_repository_webhook` constantly attempting to update the `secret` value in place / generating a diff despite us not changing the secret value at all. The solution was to pin the Github terraform provider at 2.2.1, then taint/recreate the webhooks, which stored them correctly in the state.

See also https://github.com/terraform-providers/terraform-provider-github/issues/81, which seems like the same issue fixed in a different place.
