### ISSUE TITLE
github_team --> json: cannot unmarshal object into Go struct field Organization.blog of type string

### ISSUE THREAD

**Issue by sclausson** [terraform-providers/terraform-provider-github#46] opened 2017-08-27 19:25 UTC
### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
Please list the resources as a list, for example:
- github_team

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "github_team" "foo" {
  name = "foo"
  description = "The FOO team"
  privacy = "closed"
}
```

### Expected Behavior
Github team Foo should be created and the plan should continue to be applied.

### Actual Behavior
Github team Foo is created, but `terraform apply` throws error and stops:
`github_team.foo json: cannot unmarshal object into Go struct field Organization.blog of type string`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This is the first time I have tried to create a new Github team since upgrading to tf 0.10.x. I have created multiple teams with no issues on 0.9.x

**Comment by sclausson** [comment] 2017-09-11 09:59
Recently upgraded to `terraform 10.0.4` and this fixed the issue.

**Comment by apparentlymart** [comment] 2017-09-13 17:10
Hi @sclausson! Sorry for this strange error.

I'm pretty confused by this error since it seems to suggest that the GitHub API removed an organization object whose `blog` attribute was a JSON object, rather than a string as indicated [in the API documentation](https://developer.github.com/v3/orgs/#get-an-organization).

It's also strange that upgrading Terraform core would've fixed it, since the code that produced this error is within the github client library, which is within the provider plugin rather than within core.

Do you think it's possible that this was a transient issue on GitHub's end, and was fixed in the mean time? As far as I know, there's no _good_ reason for that `blog` attribute to be anything other than a string, so all I can think of is that there was temporarily a bug in GitHub that was returning, perhaps, a `null` blog as an empty object `{}` instead.

Ideally this Terraform provider wouldn't be sensitive to this issue since it doesn't actually _use_ the organization decoded as part of a team, but this is just something done "for free" by the GitHub client library and so not easy for us to skip over. :confounded:

**Comment by sclausson** [comment] 2017-09-20 07:35
Hi @apparentlymart I agree that the error is a strange one. As you say, I'm not sure why we would even care about the `blog` attribute when creating a `team`, nor why the `blog` would be anything other than a string. I could try to reproduce by rolling back to `10.0.2` if you think that would be valuable. Otherwise I agree we can chalk it up to a transient error, close, and hope not to see it again.

**Comment by radeksimko** [comment] 2018-08-03 12:40
Hi folks,
I'm going to have close this issue as unreproducible.

I believe there may be some improvements / bug fixing to do in the upstream SDK, but we can't tell exactly how to fix it without having more data.

The provider is capable of logging all HTTP requests and responses [when `DEBUG` mode](https://www.terraform.io/docs/internals/debugging.html) is enabled. If you happen to hit the same/similar issue, please enable it and attach the log (minus any secret/sensitive data) to a new issue and we can take a look! 😉 

Thanks.

**Closed by radeksimko** 2018-08-03 12:40 UTC
Labels: bug, waiting-response
