### ISSUE TITLE
Ability to merge topics on repository?

### ISSUE THREAD

**Issue by avishnyakov** [terraform-providers/terraform-provider-github#208] opened 2019-04-10 00:31 UTC
Hi team, 

It might be nice to have ability to merge existing topics on the repository with terraform managed topics. Right now terrafrom seems to reset topics to what defined (or not) in the *.tf. That cleans up user-defined topics on repositories.

### Terraform Version
Terraform v0.11.13
+ provider.github v1.3.0

### Affected Resource(s)
-  github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "tf-test" {
  name    = "tf-test"
  private = true
}
```

### Debug Output
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ github_repository.tf-test
      topics.#:          "12" => "0"
      topics.3889168777: "xxxx" => ""

### Expected Behavior
User-defined topics aren't reset by terraform, merge option is available 

### Actual Behavior
User-defined topics aren't reset by terraform

**Comment by bltavares** [comment] 2019-04-18 13:45
That is the expected behaviour of managing resources using `terraform`. It will always consider that the correct settings are the declared on the resource definition and try to match it.

You could declare the topics on the resource, so it does not try to remove it:

```hcl
resource "github_repository" "tf-test" {
  name    = "tf-test"
  private = true
  topics = ["xxxx"]
}
```

**Comment by majormoses** [comment] 2019-05-03 15:33
> That is the expected behaviour of managing resources using `terraform`

That is true when you are talking about distinct resources but the [api call](https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository) for topics are a single api request to manage all of the topics. While we could do this by pulling down the existing topics, merging the maps, and then checking if there is a delta I actually prefer the way it currently works. Currently it shows a delta, its just a matter of adding those topics until it becomes a no-op. I think it depends on how you are looking at using terraform, I largely use terraform with github to reduce the number of people who can make manual UI changes and ensure that if someone with enough access makes changes in the UI it must be reflected with terraform or it gets reverted. I suppose we could support both options by exposing some kind of `merge_topics` attribute and default it to `false` to keep backwards compatibility.

**Comment by avishnyakov** [comment] 2019-05-05 23:39
Well, agree on everything said in topic. thanks team.

While it is desired to manage state from the source code, meaning TF would be the only source of truth, sometimes we might need "merge" behavior such as "create/update/merge if does not exist".

In this GitHub example, TF manages tags which means no UI changes can be done. TF overrides it later.
Not too bad yet not ideal as user tags go away every deployment unless they are moved into source code.

I think we can close this ticket, it's more of a process management thing. Implementing this in TF wouldn't be the right thing, I guess.

**Comment by avishnyakov** [comment] 2019-05-05 23:40
@bltavares it actually does, overriding user defined topics via UI straight to ["xxxx"]

**Comment by SpamapS** [comment] 2019-05-08 23:04
I actually wish issue labels worked the same way, so we could delete user created labels that confuse people.

**Comment by majormoses** [comment] 2019-05-09 00:07
> I actually wish issue labels worked the same way, so we could delete user created labels that confuse people.

Agreed, if you have something like `Type: Enhancement` and `Enhancement` it can get confusing, I have seen that happen especially since github bootstraps every repo with some default labels.

It would also save a ton on you API rate limit budget but we don't control their APIs sadly.

**Comment by skeggse** [comment] 2019-11-11 22:19
What's the recommended way for interacting with other tools that modify terraform-managed state? I recognize that this is a bit of an anti-pattern, but we have a mechanism for identifying repositories that match certain criteria and adding topics to those repos. Is there a good tool for mutating the `.tf` files instead of interacting with the GitHub API directly?

If not, I'd like to propose the above as a valid use-case for merging existing topics with the specific set of topics. If this seems problematic, maybe we users could specify a list of topics that can be managed external to terraform? The external management of topics makes it easy to use the existing GitHub search feature to look for the indirect criteria used to determine topics, though it is true that this is a bit of an abuse of the topic feature.

**Comment by jcudit** [comment] 2020-12-08 17:10
Closing as per [this comment](https://github.com/terraform-providers/terraform-provider-github/issues/208#issuecomment-489473573).

**Closed by jcudit** 2020-12-08 17:10 UTC
